export const POPULAR_CONVERSIONS = [
  { from: 'time_zone', to: 'time_zone', label: 'Time Zone Converter', cat: 'time_zone' },
  { from: 'usd', to: 'eur', label: 'Currency Converter', cat: 'currency' },
  { from: 'bmi', to: 'bmi', label: 'BMI Calculator', cat: 'bmi' },
  { from: 'gram', to: 'cup_flour_ap', label: 'Cooking Converter', cat: 'cooking' },
  { from: 'kilogram', to: 'pound', label: 'KG to LBS', cat: 'weight' },
  { from: 'pound', to: 'kilogram', label: 'LBS to KG', cat: 'weight' },
  { from: 'meter', to: 'foot', label: 'Meters to Feet', cat: 'length' },
  { from: 'foot', to: 'meter', label: 'Feet to Meters', cat: 'length' },
  { from: 'celsius', to: 'fahrenheit', label: 'Celsius to Fahrenheit', cat: 'temperature' },
  { from: 'fahrenheit', to: 'celsius', label: 'Fahrenheit to Celsius', cat: 'temperature' },
  { from: 'kilometer', to: 'mile', label: 'KM to Miles', cat: 'length' },
  { from: 'mg_dl', to: 'mmol_l', label: 'Blood Sugar Converter', cat: 'blood_sugar' },
  { from: 'min_per_km', to: 'min_per_mile', label: 'Pace Calculator', cat: 'pace' },
  { from: 'mile', to: 'kilometer', label: 'Miles to KM', cat: 'length' },
  { from: 'gram', to: 'ounce', label: 'Grams to Ounces', cat: 'weight' },
  { from: 'ounce', to: 'gram', label: 'Ounces to Grams', cat: 'weight' },
  { from: 'liter', to: 'us_gallon', label: 'Liters to Gallons', cat: 'volume' },
  { from: 'us_gallon', to: 'liter', label: 'Gallons to Liters', cat: 'volume' },
  { from: 'inch', to: 'centimeter', label: 'Inches to CM', cat: 'length' },
  { from: 'centimeter', to: 'inch', label: 'CM to Inches', cat: 'length' },
  { from: 'kilometer_per_hour', to: 'mile_per_hour', label: 'KMPH to MPH', cat: 'speed' },
  { from: 'mile_per_hour', to: 'kilometer_per_hour', label: 'MPH to KMPH', cat: 'speed' },
  { from: 'square_meter', to: 'square_foot', label: 'Sq Meters to Sq Feet', cat: 'area' },
  { from: 'pascal', to: 'bar', label: 'Pascals to Bar', cat: 'pressure' },
  { from: 'megabyte', to: 'gigabyte', label: 'MB to GB', cat: 'data' },
  { from: 'hertz', to: 'kilohertz', label: 'Hz to kHz', cat: 'frequency' },
  { from: 'usd', to: 'eur', label: 'USD to EUR', cat: 'currency' },
  { from: 'eur', to: 'usd', label: 'EUR to USD', cat: 'currency' },
  { from: 'horsepower', to: 'kilowatt', label: 'HP to kW', cat: 'power' },
  { from: 'degree', to: 'radian', label: 'Degrees to Radians', cat: 'angle' },
  { from: 'km_per_liter', to: 'miles_per_gallon', label: 'km/L to MPG', cat: 'fuel' },
  { from: 'us_cup', to: 'milliliter', label: 'Cups to mL', cat: 'volume' },
  { from: 'inch', to: 'millimeter', label: 'Inches to mm', cat: 'length' },
  { from: 'millimeter', to: 'inch', label: 'mm to Inches', cat: 'length' },
  { from: 'knot', to: 'mile_per_hour', label: 'Knots to MPH', cat: 'speed' },
  { from: 'hectare', to: 'acre', label: 'Hectares to Acres', cat: 'area' },
  { from: 'kilocalorie', to: 'kilojoule', label: 'Calories to kJ', cat: 'energy' },
  { from: 'kilogram', to: 'metric_ton', label: 'KG to Tons', cat: 'weight' },
];

export const POPULAR = [
  { label: "kg to lbs", cat: "weight", fu: "kilogram", tu: "pound" },
  { label: "lbs to kg", cat: "weight", fu: "pound", tu: "kilogram" },
  { label: "feet to meters", cat: "length", fu: "foot", tu: "meter" },
  { label: "miles to km", cat: "length", fu: "mile", tu: "kilometer" },
  { label: "mm to inches", cat: "length", fu: "millimeter", tu: "inch" },
  { label: "Celsius to Fahrenheit", cat: "temperature", fu: "celsius", tu: "fahrenheit" },
  { label: "Fahrenheit to Celsius", cat: "temperature", fu: "fahrenheit", tu: "celsius" },
  { label: "Liters to Gallons", cat: "volume", fu: "liter", tu: "us_gallon" },
  { label: "km/h to mph", cat: "speed", fu: "kilometer_per_hour", tu: "mile_per_hour" },
];

export const FORMULAS = [
  {
    title: "Celsius → Fahrenheit",
    code: "°F = (°C × 9/5) + 32",
    note: "Water boils at 100°C / 212°F",
    link: { cat: "temperature", from: "celsius", to: "fahrenheit" },
  },
  {
    title: "Fahrenheit → Celsius",
    code: "°C = (°F − 32) × 5/9",
    note: "Water freezes at 0°C / 32°F",
    link: { cat: "temperature", from: "fahrenheit", to: "celsius" },
  },
  {
    title: "Kilometers → Miles",
    code: "mi = km × 0.621371",
    note: "1 km ≈ 0.621 miles",
    link: { cat: "length", from: "kilometer", to: "mile" },
  },
  {
    title: "Miles → Kilometers",
    code: "km = mi × 1.60934",
    note: "1 mile ≈ 1.609 km",
    link: { cat: "length", from: "mile", to: "kilometer" },
  },
  {
    title: "Kilograms → Pounds",
    code: "lb = kg × 2.20462",
    note: "1 kg ≈ 2.205 pounds",
    link: { cat: "weight", from: "kilogram", to: "pound" },
  },
  {
    title: "Meters → Feet",
    code: "ft = m × 3.28084",
    note: "1 meter ≈ 3.281 feet",
    link: { cat: "length", from: "meter", to: "foot" },
  },
  {
    title: "Hectares → Acres",
    code: "ac = ha × 2.47105",
    note: "1 hectare ≈ 2.471 acres",
    link: { cat: "area", from: "hectare", to: "acre" },
  },
  {
    title: "Liters → US Gallons",
    code: "gal = L × 0.264172",
    note: "1 liter ≈ 0.264 gallons",
    link: { cat: "volume", from: "liter", to: "us_gallon" },
  },
];
