export const POPULAR_CONVERSIONS = [
  { from: 'time_zone', to: 'time_zone', label: 'Time Zone Converter', cat: 'time_zone' },
  { from: 'usd', to: 'eur', label: 'Currency Converter', cat: 'currency' },
  { from: 'kilogram', to: 'pound', label: 'KG to LBS', cat: 'weight' },
  { from: 'pound', to: 'kilogram', label: 'LBS to KG', cat: 'weight' },
  { from: 'meter', to: 'foot', label: 'Meters to Feet', cat: 'length' },
  { from: 'foot', to: 'meter', label: 'Feet to Meters', cat: 'length' },
  { from: 'celsius', to: 'fahrenheit', label: 'Celsius to Fahrenheit', cat: 'temperature' },
  { from: 'fahrenheit', to: 'celsius', label: 'Fahrenheit to Celsius', cat: 'temperature' },
  { from: 'kilometer', to: 'mile', label: 'KM to Miles', cat: 'length' },
  { from: 'mile', to: 'kilometer', label: 'Miles to KM', cat: 'length' },
  { from: 'gram', to: 'ounce', label: 'Grams to Ounces', cat: 'weight' },
  { from: 'ounce', to: 'gram', label: 'Ounces to Grams', cat: 'weight' },
  { from: 'liter', to: 'us_gallon', label: 'Liters to Gallons', cat: 'volume' },
  { from: 'us_gallon', to: 'liter', label: 'Gallons to Liters', cat: 'volume' },
  { from: 'inch', to: 'centimeter', label: 'Inches to CM', cat: 'length' },
  { from: 'centimeter', to: 'inch', label: 'CM to Inches', cat: 'length' },
  { from: 'kilometer_per_hour', to: 'mile_per_hour', label: 'KMPH to MPH', cat: 'speed' },
  { from: 'mile_per_hour', to: 'kilometer_per_hour', label: 'MPH to KMPH', cat: 'speed' },
  { from: 'square_meter', to: 'square_foot', label: 'Sq Meters to Sq Feet', cat: 'area' },
  { from: 'pascal', to: 'bar', label: 'Pascals to Bar', cat: 'pressure' },
  { from: 'megabyte', to: 'gigabyte', label: 'MB to GB', cat: 'data' },
  { from: 'hertz', to: 'kilohertz', label: 'Hz to kHz', cat: 'frequency' },
  { from: 'usd', to: 'eur', label: 'USD to EUR', cat: 'currency' },
  { from: 'eur', to: 'usd', label: 'EUR to USD', cat: 'currency' },
  { from: 'horsepower', to: 'kilowatt', label: 'HP to kW', cat: 'power' },
  { from: 'degree', to: 'radian', label: 'Degrees to Radians', cat: 'angle' },
  { from: 'km_per_liter', to: 'miles_per_gallon', label: 'km/L to MPG', cat: 'fuel' },
  { from: 'us_cup', to: 'milliliter', label: 'Cups to mL', cat: 'volume' },
  { from: 'inch', to: 'millimeter', label: 'Inches to mm', cat: 'length' },
  { from: 'millimeter', to: 'inch', label: 'mm to Inches', cat: 'length' },
  { from: 'knot', to: 'mile_per_hour', label: 'Knots to MPH', cat: 'speed' },
  { from: 'hectare', to: 'acre', label: 'Hectares to Acres', cat: 'area' },
  { from: 'kilocalorie', to: 'kilojoule', label: 'Calories to kJ', cat: 'energy' },
  { from: 'kilogram', to: 'metric_ton', label: 'KG to Tons', cat: 'weight' },
];
